export const brandColors = {
  inkBlack: '#14140F',
  matatuYellow: '#F2B705',
  paperWhite: '#FAF8F2',
  signalRed: '#BA1A1A',
  routeGreen: '#7DA82E',
  alertOrange: '#E8722C',
  fallbackRouteColor: '#78776f',
};

export const typography = {
  fonts: {
    display: "'Anton', sans-serif",
    body: "'Nunito Sans', 'IBM Plex Sans', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
  styles: {
    displayXl: {
      fontFamily: "'Anton', sans-serif",
      fontSize: '48px',
      fontWeight: '400',
      lineHeight: '1.1',
      letterSpacing: '0.02em',
      textTransform: 'uppercase',
    },
    headlineLg: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '32px',
      fontWeight: '700',
      lineHeight: '1.2',
      letterSpacing: '-0.01em',
    },
    headlineMd: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '24px',
      fontWeight: '700',
      lineHeight: '1.2',
    },
    titleLg: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '20px',
      fontWeight: '700',
      lineHeight: '1.4',
    },
    bodyLg: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '18px',
      fontWeight: '400',
      lineHeight: '1.5',
    },
    bodyMd: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '1.5',
    },
    bodySm: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '1.4',
    },
    dataLg: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: '18px',
      fontWeight: '600',
      lineHeight: '1.2',
    },
    dataSm: {
      fontFamily: "'IBM Plex Mono', monospace",
      fontSize: '14px',
      fontWeight: '500',
      lineHeight: '1.2',
    },
    labelCaps: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '700',
      lineHeight: '1',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
    },
    labelMd: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '12px',
      fontWeight: '600',
      lineHeight: '1.3',
    },
    labelLg: {
      fontFamily: "'Nunito Sans', sans-serif",
      fontSize: '14px',
      fontWeight: '700',
      lineHeight: '1.4',
      letterSpacing: '0.05em',
    },
  },
};

export const spacing = {
  base: '4px',
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
  liveryStripe: '6px',
  containerMargin: '16px',
  cardPadding: '24px',
  floatingOffset: '20px',
  gutter: '12px',
  unit: '8px',
  containerMax: '600px',
  navbarHeight: '64px',
};

export const shadows = {
  ambient: '0 4px 16px rgba(20, 20, 15, 0.12)',
  priority: '0 8px 32px rgba(20, 20, 15, 0.15)',
  bottomSheet: '0 -8px 32px rgba(20, 20, 15, 0.15)',
  floatingDock: '0px 8px 32px rgba(20, 20, 15, 0.15)',
  glow: '0 0 16px rgba(242, 183, 5, 0.35)',
};

export const zIndex = {
  map: 0,
  mapOverlay: 10,
  bottomSheet: 30,
  floatingControls: 40,
  floatingDock: 50,
  modal: 60,
};

export const lightTheme = {
  mode: 'light',
  colors: {
    ...brandColors,
    background: brandColors.paperWhite,
    onBackground: brandColors.inkBlack,
    surface: brandColors.paperWhite,
    onSurface: brandColors.inkBlack,
    surfaceVariant: '#e4e2dd',
    onSurfaceVariant: '#4f4633',
    surfaceContainer: '#f0eee8',
    surfaceContainerLow: '#f5f3ee',
    surfaceContainerHigh: '#eae8e2',
    surfaceContainerHighest: '#e4e2dd',
    surfaceContainerLowest: '#ffffff',
    primary: brandColors.matatuYellow,
    onPrimary: brandColors.inkBlack,
    primaryContainer: brandColors.matatuYellow,
    onPrimaryContainer: brandColors.inkBlack,
    secondary: brandColors.inkBlack,
    onSecondary: brandColors.paperWhite,
    secondaryContainer: '#e2dfd7',
    onSecondaryContainer: '#64635c',
    tertiary: brandColors.routeGreen,
    onTertiary: '#ffffff',
    error: brandColors.signalRed,
    onError: brandColors.paperWhite,
    border: '#d3c5ac',
    outline: '#817660',
    outlineVariant: '#d3c5ac',
    shadow: shadows.ambient,
  },
  borders: {
    width: '1px',
    style: 'solid',
    card: '1px solid #d3c5ac',
    overlay: '1px solid #d3c5ac',
    divider: '1px solid #e4e2dd',
  },
  radii: {
    none: '0px',
    card: '24px',
    button: '9999px',
    sheet: '32px 32px 0 0',
    chip: '9999px',
    pill: '9999px',
    full: '9999px',
    lg: '32px',
    xl: '48px',
  },
  shadows,
  zIndex,
  typography,
  spacing,
};

export const darkTheme = {
  mode: 'dark',
  colors: {
    ...brandColors,
    background: brandColors.inkBlack,
    onBackground: '#FAF8F2',
    surface: '#1c1c17',
    onSurface: '#FAF8F2',
    surfaceVariant: '#262620',
    onSurfaceVariant: '#c9c6bd',
    surfaceContainer: '#23231d',
    surfaceContainerLow: '#1f1f1a',
    surfaceContainerHigh: '#2e2e26',
    surfaceContainerHighest: '#38382f',
    surfaceContainerLowest: '#14140F',
    primary: brandColors.matatuYellow,
    onPrimary: brandColors.inkBlack,
    primaryContainer: brandColors.matatuYellow,
    onPrimaryContainer: brandColors.inkBlack,
    secondary: '#c8c6c1',
    onSecondary: brandColors.inkBlack,
    secondaryContainer: '#494945',
    onSecondaryContainer: '#e2dfd7',
    tertiary: brandColors.routeGreen,
    onTertiary: '#ffffff',
    error: brandColors.signalRed,
    onError: brandColors.paperWhite,
    border: '#38382f',
    outline: '#9c8f78',
    outlineVariant: '#4f4633',
    shadow: shadows.priority,
    glow: shadows.glow,
  },
  borders: {
    width: '1px',
    style: 'solid',
    card: '1px solid #38382f',
    overlay: '1px solid #38382f',
    divider: '1px solid #262620',
  },
  radii: {
    none: '0px',
    card: '24px',
    button: '9999px',
    sheet: '32px 32px 0 0',
    chip: '9999px',
    pill: '9999px',
    full: '9999px',
    lg: '32px',
    xl: '48px',
  },
  shadows,
  zIndex,
  typography,
  spacing,
};

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};

export default lightTheme;
